#ifndef LITTLEVULKANENGINE_SOURCE_TOOLS_CONSTANTS_HPP
#define LITTLEVULKANENGINE_SOURCE_TOOLS_CONSTANTS_HPP


#ifdef NDEBUG
#define LVE_RELEASE
#else
#define LVE_DEBUG
#endif

static constexpr float DEFAULT_QUEUE_PRIORITY = 0.0f;
static constexpr int MAX_FRAMES_IN_FLIGHT = 2;

#endif //LITTLEVULKANENGINE_SOURCE_TOOLS_CONSTANTS_HPP
