#ifndef LITTLEENGINE_CONSTANTS_HPP
#define LITTLEENGINE_CONSTANTS_HPP


#ifdef NDEBUG
#define ENGINE_RELEASE
#else
#define ENGINE_DEBUG
#endif

const float DEFAULT_QUEUE_PRIORITY = 0.0f;

#endif //LITTLEENGINE_CONSTANTS_HPP
