#ifndef LITTLEVULKANENGINE_SOURCE_TOOLS_CONSTANTS_HPP
#define LITTLEVULKANENGINE_SOURCE_TOOLS_CONSTANTS_HPP


#ifdef NDEBUG
#define LVE_RELEASE
#else
#define LVE_DEBUG
#endif


#endif //LITTLEVULKANENGINE_SOURCE_TOOLS_CONSTANTS_HPP
